---
# book-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
      - name: book-service
        image: c0875728/simple_library_app:book_service-latest
        ports:
        - containerPort: 5000
        env:
        - name: BOOK_SERVICE_HOST
          value: "0.0.0.0"
        - name: BOOK_SERVICE_PORT
          value: "5000"
---
# author-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-service
spec:
  selector:
    matchLabels:
      app: author-service
  template:
    metadata:
      labels:
        app: author-service
    spec:
      containers:
      - name: author-service
        image: c0875728/simple_library_app:author_service-latest
        ports:
        - containerPort: 5001
        env:
        - name: AUTHOR_SERVICE_HOST
          value: "0.0.0.0"
        - name: AUTHOR_SERVICE_PORT
          value: "5001"
---
# api-gateway.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: c0875728/simple_library_app:api_gateway-latest
        ports:
        - containerPort: 5002
        env:
        - name: API_SERVICE_HOST
          value: "0.0.0.0"
        - name: API_SERVICE_PORT
          value: "5002"
        - name: BOOK_SERVICE_HOST
          value: "book-service"
        - name: BOOK_SERVICE_PORT
          value: "5000"
        - name: AUTHOR_SERVICE_HOST
          value: "author-service"
        - name: AUTHOR_SERVICE_PORT
          value: "5001"
---
# web-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: web-frontend
        image: c0875728/simple_library_app:web_frontend-latest
        ports:
        - containerPort: 5003
        env:
        - name: FE_SERVICE_HOST
          value: "0.0.0.0"
        - name: FE_SERVICE_PORT
          value: "5003"
        - name: API_GATEWAY_HOST
          value: "api-gateway"
        - name: API_GATEWAY_PORT
          value: "5002"
