---
# book-service-service
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book-service
  ports:
  - port: 5000
    targetPort: 5000
---
# author-service-service
apiVersion: v1
kind: Service
metadata:
  name: author-service
spec:
  selector:
    app: author-service
  ports:
  - port: 5001
    targetPort: 5001
---
# api-gateway-service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 5002
    targetPort: 5002
---
# web-frontend-service
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  type: LoadBalancer
  selector:
    app: web-frontend
  ports:
  - port: 5003
    targetPort: 5003