apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.authorsPort }}
        env:
        - name: AUTHOR_SERVICE_HOST
          value: "{{ .Values.authorsUrl }}"
        - name: AUTHOR_SERVICE_PORT
          value: "{{ .Values.authorsPort }}"