apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.apiPort }}
        env:
        - name: API_SERVICE_HOST
          value: "{{ .Values.urls.api }}"
        - name: API_SERVICE_PORT
          value: "{{ .Values.ports.api }}"
        - name: BOOK_SERVICE_HOST
          value: "{{ .Values.urls.books }}"
        - name: BOOK_SERVICE_PORT
          value: "{{ .Values.ports.books }}"
        - name: AUTHOR_SERVICE_HOST
          value: "{{ .Values.urls.authors }}"
        - name: AUTHOR_SERVICE_PORT
          value: "{{ .Values.ports.authors }}"