apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: {{ .Values.booksPort }}
    targetPort: {{ .Values.booksPort }}