apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
#  type: LoadBalancer
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: {{ .Values.ports.fe }}
    targetPort: 5003